language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master
    - develop
    - spike/travis-ci-auto-script

before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo apt-get install -qq python-numpy python-scipy
 - sudo dpkg -L python-opencv

install:
  #- "pip install --upgrade pip"
  # - "cd src/experiments/perspective_calibration"
  # - "python setup.py install"
  # - "pip install ."

script:
  # - nosetests -w tests/ --with-coverage --cover-package point
  - bash run_tests.sh
